services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=fofoqueirodb'
      - 'POSTGRES_PASSWORD=fofoqueiro'
      - 'POSTGRES_USER=fofoqueiro'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
